### ISSUE TITLE
Mocking with request parameters

### ISSUE THREAD

**Issue by vishvodhay** [lwsjs/local-web-server#101]
I'm trying to construct an endpoint/route which takes in query string params and mocks do not respond to those requests

/v1/api/type?keyword=abc

It's only capable to read until "/v1/api/type" and ignore the rest. How can I leverage query params in mocking with lws?

**Comment by 75lb** [comment]
within your middleware function, the query string params should be available on [ctx.request.query](https://github.com/koajs/koa/blob/master/docs/api/request.md#requestquery)..
