### ISSUE TITLE
can i set the port in terminal ?

### ISSUE THREAD

**Issue by lovanya** [lwsjs/local-web-server#104]
I want to set the port like this

```bush
  ws --port=8080
```
can u make it happen ?

**Comment by 75lb** [comment]
The command you pasted works fine. Are you saying that command fails for you? If so, please describe how I reproduce the issue. Which OS are you on? Which version of local-web-server and node are you using?

**Comment by lovanya** [comment]
@75lb oooh, I'm sorry,  didn't try last time. just saw the introduce from npm. ))
