### ISSUE TITLE
-z or --compress not compressing any file in browser

### ISSUE THREAD

**Issue by kumargauravin** [lwsjs/local-web-server#107]
Hi Team,
Some time back when we used --compress option we could see content-encoding: gzip in response headers but now serving an angular app we see no file is served giziped.

Please explain if something have changed over time.

Regards,
Kumar

**Comment by 75lb** [comment]
try reducing the compression threshold (1024B by default), e.g. 

```
$ ws --compress --compress.threshold 500
```
