### ISSUE TITLE
Access to fetch blocked by CORS policy

### ISSUE THREAD

**Issue by shaunc869** [lwsjs/local-web-server#110]
I'm getting Access to fetch at URL_HERE from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea what I'm doing wrong? Thanks!

**Comment by 75lb** [comment]
can you post a reproduction case please - the full `ws` command you are running plus any config file please..

**Comment by shaunc869** [comment]
In my case this was the server not returning the proper headers.
