### ISSUE TITLE
A typo in 'CLI usage' wiki page

### ISSUE THREAD

**Issue by gamtiq** [lwsjs/local-web-server#111]
It seems there is a typo inside [CLI usage](https://github.com/lwsjs/local-web-server/wiki/CLI-usage) wiki page in description of middleware stack. Namely, Cors middleware is mentioned twice. The second mention is the following:
> Cors             Support for HTTP Range Requests.

I suppose there should be another middleware (Range?).

**Comment by 75lb** [comment]
Fixed by https://github.com/lwsjs/range/commit/840bcca3343b85477590189daddfe96fd07ebdab. Wiki updated, thanks.
