### ISSUE TITLE
Rewrite & Images

### ISSUE THREAD

**Issue by skipjack** [lwsjs/local-web-server#121]
I'm seeing an issue with `--rewrite` in the latest version where image data is malformed. I updated the rewrite wildcard syntax which worked fine but then I noticed all the images would come back malformed and not render. Reverting back to v2 fixed the issue.

**Comment by 75lb** [comment]
Fixed and released in lws-rewrite v2.0.4, please re-install local-web-server v3 to pick up the change - thanks for letting me know. 👍

**Comment by skipjack** [comment]
Awesome, I'll test soon.
