### ISSUE TITLE
404 when query params have periods in them.

### ISSUE THREAD

**Issue by stormmuller** [lwsjs/local-web-server#122]
I'm getting some strange behavior when I hit a URL with a period in a query value.

Example: `https://my-fake-site/login?callback=asfasdf.asdf` I get a 404

When I hit just `https://my-fake-site/login?callback=asfasdf` it's golden...

For context, I'm working with a SPA

Originally I ran: `ws --spa index.html`
Then I thought the URL was being interpreted as a static file due to the period. So I added the `--spa.asset-test-fs` flag. 

Making the final command `ws --spa index.html --spa.asset-test-fs` Which still doesn't work

**Comment by 75lb** [comment]
interesting.. I'll try and reproduce it in a min..

**Comment by 75lb** [comment]
i can't reproduce this.. if I launch a server with this command, the `/login?callback=asfasdf.asdf` path returns 404.

```
$ ws --spa index.html
```

But with this command the same path works fine. 

```
$ ws --spa index.html --spa.asset-test-fs
```

Are you sure you have the latest local-web-server installed? Just reinstall it just be sure you have the latest of everything, including the dep tree. Which OS and node version are you using?

**Comment by 75lb** [comment]
FYI, you spotted [a separate bug](https://github.com/lwsjs/spa/issues/3)

**Comment by 75lb** [comment]
https://github.com/lwsjs/spa/issues/3 is now fixed. If you reinstall, the fullstop in your querystring won't break the default asset-test, meaning you won't need to the `--spa.asset-test-fs` flag.

**Comment by stormmuller** [comment]
That was really quick! thanks.

**Comment by 75lb** [comment]
no problem, let me know if you find anything else.
