### ISSUE TITLE
Document the --open option

### ISSUE THREAD

**Issue by dtslvr** [lwsjs/local-web-server#129]
I've just found the `--open` option by accident (https://github.com/lwsjs/local-web-server/commit/c77b6234bc7d6d209254ec6d92579c17ee44a1f6). Maybe add it to the readme?

**Comment by 75lb** [comment]
I've added the following link to the wiki: 

* [How to launch a browser together with the server](https://github.com/lwsjs/local-web-server/wiki/How-to-launch-a-browser-together-with-the-server)

Let me know if you find anything else. 👍

**Comment by dtslvr** [comment]
Cool, thank you @75lb!
