### ISSUE TITLE
live reload/refresh local web server.

### ISSUE THREAD

**Issue by gsaini** [lwsjs/local-web-server#131]
Can you please add an option of live reload on it?

Use case - We created a mock server using local web server. If we change anything on those mocks it should reload/refresh the server. (Expecting similar functionality as nodemon)

**Comment by 75lb** [comment]
can you not use `nodemon` together with `ws`?

**Comment by 75lb** [comment]
Closing. I don't plan to add and maintain `nodemon` style functionality to local-web-server. If `nodemon` does not restart the `ws` process as required, please raise an issue with the nodemon project.
