### ISSUE TITLE
What is the advantage over http-server package.

### ISSUE THREAD

**Issue by qiulang** [lwsjs/local-web-server#133]
Hi this is a question.

I have been using https://github.com/http-party/http-server until recently someone told me I may give  local-web-server a try. So I was wondering what is the advantage over http-server package ?

Thanks!

**Comment by 75lb** [comment]
Sorry, I have never used http-server before. You can find plenty of information about local-web-server on [the wiki](https://github.com/lwsjs/local-web-server/wiki). Local-web-server is regularly maintained, supports HTTP2 and is 100% customisable. There is a plugin available to support most features, or you can create your own middleware plugin.

**Comment by 75lb** [comment]
@qiulang  did you try local-web-server? What is your opinion?

**Comment by qiulang** [comment]
I have tried it but the hard part is to persuade my team members to try it instead of  http-server. Hence the question.

**Comment by Ksenich** [comment]
The main issue with http-server right now is that [ecstatic](https://github.com/jfhbrook/node-ecstatic), for which http-server is basically a wrapper, is no longer [developed](https://github.com/jfhbrook/node-ecstatic/issues/259).
