### ISSUE TITLE
Configured mime types are not used

### ISSUE THREAD

**Issue by Toastgeraet** [lwsjs/local-web-server#144]
Hey,
i created a lws.config.js to customize mime types, because my browser wont load javascript files: it complain about the mime type being text/plain.

Now the config output by 'ws --config' looks fine, but when tested in browser, the local web server still returns 'text/plain' for .js files.

```
{
  port: 8000,
  moduleDir: [
    '.',
    'C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\local-web-server'
  ],
  modulePrefix: 'lws-',
  stack: MiddlewareStack(15) [
    BasicAuth,      BodyParser,
    RequestMonitor, Log,
    Cors,           Json,
    Compress,       Rewrite,
    Blacklist,      ConditionalGet,
    Mime,           Range,
    SPA,            Static,
    Index
  ],
  mime: { 'application/javascript': [ 'js', 'mjs' ] },
  view: CliView {}
}
```

**Comment by 75lb** [comment]
This is strange. By default, local-web-server will return the correct MIME type for Javascript (`application/javascript`). If it did not, thousands of people would be reporting a bug - including myself.

Please post a full reproduction case - code and commands I can run to see this issue failing for myself.

**Comment by 75lb** [comment]
Closing for now as stale.
