### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by lucasravy** [lwsjs/local-web-server#151]
Hey guys!

Quick question: is there an official Docker image for local-web-server?
If don't, what do you think about create one and make it available for the community? Maybe I could try help with this.

:grin:

**Comment by lucasravy** [comment]
Howdy :grin:!

I've created a docker image and I would like to know if you guys have any suggestions for it. The image contains: _Alpine Linux_, _Node_, _Npm_ and _local-web-server_ provided by npm install command. It work pretty well in our solution. 

Link for the image: https://hub.docker.com/repository/docker/lucasravy/local-web-server-alpine 

What do you guys think about create a section in README file with instructions of how run the server using Docker? I could do that PR, if the maintainers think that is a good idea.

Please, let me know.

Thanks!

**Comment by 75lb** [comment]
Hi, this particular project covers only the Javascript codebase - whether `ws` is deployed on Linux, Mac or Windows via Docker, VirtualBox or Vagrant is a usage decision beyond the scope of this project.. 

However, your image sounds useful! Feel create to create a "Deployment" section at the [bottom of the Wiki](https://github.com/lwsjs/local-web-server/wiki) and add a link to a separate Wiki page (which you'll also need to create) documenting your image. 

The new section would look something like this: 

## Deployment

* Link to my new page describing my Docker image
