### ISSUE TITLE
How can I replace body content using a middleware?

### ISSUE THREAD

**Issue by simplenotezy** [lwsjs/local-web-server#154]
I am trying to chain two middlewares - the native built in one, and a custom one I made to replace some text in the response body.

**mw-replace-urls.js**
```
class ReplaceURLs {
  middleware () {
    return async (ctx, next) => {
			ctx.response.body = ctx.response.body.replaceAll('TEST', 'I-AM-REPLACED'); // cannot read property 'replaceAll' of undefined

			await next();
    }
  }
}

module.exports = ReplaceURLs
```

And this is how I run the stacks:

    yarn ws -d dist --stack mw-replace-urls.js lws-static 

It will fail with:

```
TypeError: Cannot read property 'replaceAll' of undefined
    at /Users/mf/Projects/my-project/mw-replace-urls.js:5:42
```

What am I doing wrong?

**Comment by 75lb** [comment]
try placing your custom middleware *before lws-static in the `--stack`
list.. order is significant in a middleware chain

**Comment by simplenotezy** [comment]
Okay, so I guess the main issue was that I was loading mw-replace-urlsjs after lws-static, and it should be **before**. Anyhow. Now my issue is that `ctx.response.body` is undefined, despite the content rendering just fine. Why is `ctx.resposne.body` undefined?

**Comment by simplenotezy** [comment]
updated original post for clarification

**Comment by 75lb** [comment]
see lws-body-parser..

**Comment by simplenotezy** [comment]
@75lb Thanks for so prompt replies. I have tried looking at https://github.com/koajs/bodyparser and also replacing rawBody like this:

    ctx.response.rawBody = ctx.response.rawBody.replace('sense', 'I-AM-REPLACED');

But doesn't seem to work.

**Comment by simplenotezy** [comment]
@75lb I have tried many different variations, and also read https://github.com/lwsjs/local-web-server/wiki/How-to-access-the-body-of-an-incoming-request (although not very documented). I'm stuck at the moment unfortunately.

**Comment by simplenotezy** [comment]
@75lb I might need to use:

app.use(bodyParser({
        "enableTypes": ['json', 'form', 'text'],
    }));

Somewhere in my middleware to allow `rawBody` to be present, but now sure where/how I would add this in my middelware, given that it is a native module. Any suggestions?

**Comment by 75lb** [comment]
I created [an example project](https://github.com/lwsjs/examples/tree/master/middleware-edit-response-body) to demonstrate how response editing is done.. Any questions, let me know.

**Comment by simplenotezy** [comment]
Ah that's cool, thank you very mcuh @75lb!

**Comment by 75lb** [comment]
you're welcome
