### ISSUE TITLE
How to enable verbose option while using API of lws?

### ISSUE THREAD

**Issue by aniket7824** [lwsjs/local-web-server#161]
While using the CLI variant, all the verbose is appearing in the console including verbose related to URL rewrite. How to get the same functionality in the case of an API variant of lws?

**Comment by 75lb** [comment]
Listen for [`verbose` event](https://github.com/lwsjs/lws/blob/master/doc/lws.md#verbose-key-value) on the `localWebServer` instance..

Quickly, from the top of my head - something like this:

```js
import LocalWebServer from 'local-web-server'

const options = { /* your options, port, directory etc */ }
const lws = LocalWebServer.create(options)

lws.on('verbose', (key, value) => {
  // process verbose info
}
```

**Comment by aniket7824** [comment]
Thanks @75lb. That works!
