### ISSUE TITLE
what's going on here?

### ISSUE THREAD

**Issue by larryw3i** [lwsjs/local-web-server#163]
![Screenshot from 2021-07-06 11-42-45](https://user-images.githubusercontent.com/24457116/124539275-b5465480-de4f-11eb-9c04-1fef80b21de5.png)

**Comment by 75lb** [comment]
the badges have not loaded.. try refreshing the page, it should look like this: 

<img width="947" alt="Screenshot 2021-07-06 at 09 52 45" src="https://user-images.githubusercontent.com/1247980/124571747-fcc4e480-de3f-11eb-8ceb-73ebd46d2bf6.png">
