### ISSUE TITLE
Cannot consume package from TypeScript

### ISSUE THREAD

**Issue by bjornharrtell** [lwsjs/local-web-server#168]
Results in:

error TS2307: Cannot find module 'local-web-server' or its corresponding type declarations.

5 import LocalWebServer from 'local-web-server';

**Comment by 75lb** [comment]
does this thread help? 
https://github.com/microsoft/TypeScript/issues/33079

**Comment by 75lb** [comment]
There is a note about it in the Typescript docs: 

> Note: node module resolution is the most-commonly used in the TypeScript community and is recommended for most projects. If you are having resolution problems with imports and exports in TypeScript, try setting moduleResolution: "node" to see if it fixes the issue.

Taken from [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies)

**Comment by bjornharrtell** [comment]
That's unfortunately what I have already.

**Comment by bjornharrtell** [comment]
But reading a bit more on https://github.com/microsoft/TypeScript/issues/33079 it seems it might need something in an upcoming relase. If you want to be more compatible with what is out now, I think it would work if there was a cjs exports alternative in the package, I got a few of those kind of dependencies already.

**Comment by 75lb** [comment]
as a general rule, all my projects have support for `require` and CommonJS but unfortunately I had to drop CommonJS support in [local-web-server v5.0.0](https://github.com/lwsjs/local-web-server/releases/tag/v5.0.0) due to rollup (used to create the CJS build) not having support for dynamic imports (required to load middleware plugins).

I will look into the Typscript issue.. if it's not too inconvenient, you could use [v4.2](https://github.com/lwsjs/local-web-server/releases) until the Typescript people release a fix..

**Comment by bjornharrtell** [comment]
No problem, I'll close this for now.

**Comment by 75lb** [comment]
I got it to work with the latest local-web-server using [typescript 4.5 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/).

With this code: (index.ts)

```js
import LocalWebServer from 'local-web-server'

const lws = new LocalWebServer()
```

and this config: (tsconfig.json)

```json
{
  "compilerOptions": {
    "module": "node12",
  }
}
```

Running `tsc` produced this output: (index.js)

```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const local_web_server_1 = __importDefault(require("local-web-server"));
const lws = new local_web_server_1.default();
```
