### ISSUE TITLE
Rewrite wildcard does not create the match

### ISSUE THREAD

**Issue by tkosci** [lwsjs/local-web-server#175]
Hello,

I am facing issue with rewrite wildcard.

When I use:

`ws --port 8080 --spa index.html --directory build --rewrite "/api/(.*) -> http://localhost:5000/api/$1" --verbose.include middleware.rewrite`

The urls do not match as seen in screenshot below:

![image](https://user-images.githubusercontent.com/25982854/178714658-98986d7f-3dbf-4f24-ba4e-d0fb5d15080c.png)

However, in debugging tool the wildcard matches just fine:
`npx lws-rewrite '/api/(.*)' 'http://localhost:5000/api/$1' '/api/count_data/'` ->
`http://localhost:5000/api/count_data/`

Any idea what is the issue here? Thanks

**Comment by 75lb** [comment]
Hi, are you on *nix? If so, always use single quotes as double-quotes have special meaning with strings that contain `$` (variable expansion).. 

try this instead (no double quotes)

```
ws --port 8080 --spa index.html --directory build --rewrite '/api/(.*) -> http://localhost:5000/api/$1' --verbose.include middleware.rewrite
```

**Comment by tkosci** [comment]
Thank you, that fixed it for me!
