### ISSUE TITLE
Server shuts down

### ISSUE THREAD

**Issue by mustafaekim** [lwsjs/local-web-server#178]
Hello,

I start the server but it does not  stay open, rather  the script ends right after the server starts up. Please see the code below:

```
import LocalWebServer from 'local-web-server'
//var LocalWebServer = require("local-web-server");

async function start(){
  //const LocalWebServer = require("local-web-server")
  const ws = await LocalWebServer.create({
    port: 8000,
    directory: '../public',
    hostname: "192.168.1.96"  
  })

  console.log(`Webserver running...`)
};

start();
```

When I run this peace of code through the "node start-server.js" command, I am seeing the log "Webserver running..." log on the console but right after that the script ends and the server does not live any more.

Does anyone have a guesss why the script is terminated rather than waiting to respond incoming requests?

**Comment by 75lb** [comment]
shouldn't it be `await start()` at the bottom?

**Comment by 75lb** [comment]
> Nope, you cannot use await inside the file but only inside an async function.

You can.. [top-level await](https://arjunphp.com/how-to-use-top-level-await-in-node-js/) has been available in Node since at least v14.. You must `await` your `start` method.

**Comment by 75lb** [comment]
Closing for now, if you confirm it's definitely a bug in local-web-server let me know..
