### ISSUE TITLE
Cannot find the port when running in docker

### ISSUE THREAD

**Issue by Superhzf** [lwsjs/local-web-server#179]
Hi there,

This works fine locally. However, when I try to move it into a docker container, the server cannot find the correct port. My docker file looks like this:

```
FROM node:18.12.1

ENV NODE_ENV=production
WORKDIR /fronted
RUN npm install -g local-web-server
COPY . .
CMD [ "ws", "--port 30" ]
```
Then, if I run `docker run -dp 30:30 frontend-server`, and then `docker logs -f <container-id>` it shows  `Listening on http://8ab29995624f:null, http://127.0.0.1:null, http://172.17.0.2:null`. I expect `null` to be `30`.

**Comment by 75lb** [comment]
Try changing this line

```
CMD [ "ws", "--port 30" ]
```

to this

```
CMD [ "ws", "--port", "30" ]
```

**Comment by Superhzf** [comment]
> Try changing this line
> 
> ```
> CMD [ "ws", "--port 30" ]
> ```
> 
> to this
> 
> ```
> CMD [ "ws", "--port", "30" ]
> ```

Thank you so much for your quick reply, that works! 

Now, in the docker it shows `Listening on http://5f80a3af8967:30, http://127.0.0.1:30, http://172.17.0.2:30`. But I can only open the page with `http://127.0.0.1:30` but `http://5f80a3af8967:30` and `http://172.17.0.2:30` are not loading up, is it normal? If I run without docker, all three sites work perfectly.

**Comment by 75lb** [comment]
> `http://5f80a3af8967:30` and `http://172.17.0.2:30` are not loading up, is it normal? If I run without docker, all three sites work perfectly.

it _could_ be normal - i don't know how you have networking/routing/DNS/WIN etc set up on your machine or container.. Closing as beyond the scope of ws..
