### ISSUE TITLE
Add the option to set a custom process title

### ISSUE THREAD

**Issue by 75lb** [lwsjs/local-web-server#186]
Something more useful than `node`. [Backstory](https://github.com/lwsjs/local-web-server/discussions/181).

**Comment by IgeNiaI** [comment]
Hello. Is there any update to this? I like stopping processes by name in my scripts, but `node` is too generic to ensure that only the correct process is stopped.

**Comment by 75lb** [comment]
Yes, it has been implemented in the next version of local-web-server (WIP) but that's not ready yet. So I just backported the feature to the current live version. 

If you reinstall then run `ws --help`, you should see `--title` in the list of options..
