### ISSUE TITLE
Does rewrite works on Windows?

### ISSUE THREAD

**Issue by dereklin** [lwsjs/local-web-server#58]
I am using Windows 7 and local-web-server 1.2.7.  When I do 
```
ws
```
The site is running ok.

When I do:
```
ws --rewrite '/yeah/* -> http://localhost:9000/$1'
```
I get 
```
The filename, directory name, or volume label syntax is incorrect.
```
I tried changing the path many times but still got the same error.

**Comment by 75lb** [comment]
on Windows you need to use double-quotes.. I've no idea why, I don't know the platform very well. 

```
$ ws --rewrite "/yeah/* -> http://localhost:9000/$1"
```

**Comment by dereklin** [comment]
@75lb Thanks!
