### ISSUE TITLE
Missing rewrite config

### ISSUE THREAD

**Issue by baklanovavpulter** [lwsjs/local-web-server#59]
`npm install local-web-server`

> -- local-web-server@1.2.7

`call "node_modules/.bin/ws" --directory "wwwroot" --rewrite "/test.html -> /_test.html" --config`

> {
  "port": 8000,
  "directory": "wwwroot",
  "forbid": [],
  "rewrite": [
    {
      "from": "/test.html",
      "to": "/_test.html"
    }
  ]
}

Save this to ".local-web-server.json" in current folder.
`call "node_modules/.bin/ws" --config`

> {
  "port": 8000,
  "directory": "wwwroot",
  "forbid": [],
  "rewrite": []
}

?

**Comment by 75lb** [comment]
Hi, can you show me the `.local-web-server.json` file which is failing please? 

Also, this issue is resolved in v2 which is in progress and [available for preview](https://github.com/lwsjs/local-web-server/tree/next).. any feedback welcome.
