### ISSUE TITLE
Please how can we use lws to server both http and https from the same port, like httpolyglot?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [lwsjs/local-web-server#61]
Please how can we use lws to server both http and https from the same port, like https://github.com/mscdex/httpolyglot ?

Thanks

**Comment by 75lb** [comment]
sorry, lws does not support that feature. HTTP is served over port 80, HTTPS over port 443 - I don't understand why anyone would want to run both on the same port.

**Comment by CharlesOkwuagwu** [comment]
just for testing on localhost

**Comment by 75lb** [comment]
could you run two instances of lws - one on port 80, one on port 443?

**Comment by CharlesOkwuagwu** [comment]
no, we don't typically have access to the default ports for localhost.

Lws is so well suited for this task, as it gives full control of the pile-line, if only i could figure out how to bring in the concepts from httpolyglot into lws, it would be an ideal fit for testing https on
 localhost

**Comment by 75lb** [comment]
how about running an http lws on 8000 and an https lws on 8100? I still don't understand why running both on the same port is necessary - it would never happen in a production environment..
