### ISSUE TITLE
error message placement

### ISSUE THREAD

**Issue by 75lb** [lwsjs/local-web-server#7]
err msg currently appears in Connection column, put somewhere else..

```
$ ws
serving at http://localhost:8000
Requests   Data        Connections
24         50.60 KB    Error: ENAMETOOLONG, stat '/Users/Lloyd/Documents/blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah'
```

**Comment by mikich** [comment]
Have an issues with running server...:

local-user-mac:ws local-user$ npm start

> web-sever@1.0.0 start /Users/local-user/work/ws
> ws

sh: ws: command not found

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! web-sever@1.0.0 start: `ws`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the web-sever@1.0.0 start script 'ws'.
npm ERR! This is most likely a problem with the web-sever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ws
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-sever
npm ERR! There is likely additional logging output above.
