### ISSUE TITLE
rewrite middleware doesn't treat pattern `:0` correctly

### ISSUE THREAD

**Issue by lbcat** [lwsjs/local-web-server#70]
Hi, I'm very helped by `local-web-server` everyday.

I found a strange behavior with rewrite feature when I configure `lws.config.js` as

```js
module.exports = {
  port: 8000,
  rewrite: [
    { from: "/api/*", "to": "http://localhost:9000/$1" }
  ]
}
```

and I start `ws` and send request to `localhost:8000/api/messages?time=2017-01-01T12:00`, then I found a strange replacement in `ws` verbose logs

```js
{ 'middleware.rewrite.proxy': 
   { from: '/api/messages?time=2017-01-01T12:00',
     to: 'http://localhost:9000/messages?time=2017-01-01T12messages0' } }
```

Near `:0` in the original time-string, a string `messages` (seems to be captured by `*`) appears again.

I also tried to send another string `localhost:8000/api/messages?time=2017-01-01T12:10` then `ws` logs

```js
{ 'middleware.rewrite.proxy': 
   { from: '/api/messages?time=2017-01-01T12:10',
     to: 'http://localhost:9000/messages?time=2017-01-01T12:10' } }
```

It looks like a correct replacement, so I think the pattern `:0` causes the broken replacement.

**Comment by 75lb** [comment]
thanks for letting me know! Fixed and released in local-web-server v2.2.4.

Let me know if you find anything else 👍
