### ISSUE TITLE
rewrite syntax reference

### ISSUE THREAD

**Issue by mscalora** [lwsjs/local-web-server#73]
Are there good docs somewhere for the rewrite syntax? I thought maybe koa-rewrite was being used but I couldn't find very much there either.

I'm trying to ignore url search parameters but not other suffixes.

`/test.html -> /real.html`     doesn't match anything with search string like `/test.html?q=test`

`/test.html?* -> /real.html`     lets anything through, like` /test.htmlNOT`

Is `?` a meta character? I tried a few things to escape it but nothing I could think of worked.

**Comment by 75lb** [comment]
have you tried [here](https://github.com/lwsjs/local-web-server/wiki/How-to-rewrite-URLs-to-local-or-remote-destinations)?

**Comment by mscalora** [comment]
Yes, I saw that, it appears to only brush the topic somewhat lightly. The question mark character appears to act in a special way but is not mentioned, nor is escaping meta characters. Is there any special support for search query parameters? Many systems have pseudo-regexp support so I was wondering if ? was affected by something like that.

**Comment by 75lb** [comment]
did you click the "express routing syntax" link?
https://expressjs.com/en/guide/routing.html

**Comment by mscalora** [comment]
No I didn't see that despite looking at that page at least three times. Sorry, thanks, just what I needed.

**Comment by 75lb** [comment]
no worries.. it's a wiki, so you can edit things if you think something is not clear enough.
