### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by deepdad** [lwsjs/local-web-server#78]
Hi, I have followed the instructions up to ubuntu@ip-172-31-28-191:~/demo/www$ ws --https
Serving at https://ip-172-31-28-191:8000, https://127.0.0.1:8000, https://172.31.28.191:8000
on AWS, but only get 404 on the public web on a AWS ubuntu 16 server. 

$ wget http://ip-172-31-28-191:8000
--2017-12-05 13:42:31--  http://ip-172-31-28-191:8000/
Resolving ip-172-31-28-191 (ip-172-31-28-191)... 172.31.28.191
Connecting to ip-172-31-28-191 (ip-172-31-28-191)|172.31.28.191|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13979 (14K) [text/html]
Saving to: ‘index.html.2’

index.html.2        100%[===================>]  13.65K  --.-KB/s    in 0s      

2017-12-05 13:42:31 (400 MB/s) - ‘index.html.2’ saved [13979/13979]

On AWS, I have all outbound traffic on all ports open.

**Comment by 75lb** [comment]
This is not a bug with local-web-server and I'm not sure what to suggest - I have no experience with AWS.. I can't reproduce this.
