### ISSUE TITLE
Is it possible to redirect 'http' to https'?

### ISSUE THREAD

**Issue by rethna2** [lwsjs/local-web-server#82]
This simple server really works for me (spa and api proxy support) and many thanks to the developers and maintainers. 
Presently having it as below:
`ws --spa index.html --rewrite '/api/* -> https://backendapi.com/api/$1' -p 8080 `

Is it possible to redirect 'http' to https'? I am not reporting it as issue, but just asking as question. Would really appreciate any answer.

**Comment by 75lb** [comment]
What exactly do you want to happen, could you spell it out to me please? 

Do you want one of the following or something else?

1.  a request to `http://localhost:8000` to return this response:

    ```
    HTTP/1.1 301 Moved Permanently
    Location: https://localhost:8000
    ```

2. a request to `http://localhost:8000` to be transparently proxied by the server to `https://localhost:8000`

**Comment by rethna2** [comment]
I want the  second one. I am getting a 404, for http://localhost:8000. I want to redirect to 'https://localhost:8000'.

**Comment by 75lb** [comment]
The second example i gave *is not a redirect*, it is a proxy. If you want to proxy, [read this](https://github.com/lwsjs/local-web-server/wiki/How-to-proxy-all-HTTP-requests-to-HTTPS).

**Comment by rethna2** [comment]
Yes. You are correct. Thanks for the help.

**Comment by 75lb** [comment]
you're welcome
