### ISSUE TITLE
ws: command not found

### ISSUE THREAD

**Issue by 462960** [lwsjs/local-web-server#84]
local-web-server installed, I run `ws --mock local-server.js` and terminal answers: "ws: command not found"

**Comment by 75lb** [comment]
did you install local-web-server globally? You need to install it with this command. 

```
$ npm install -g local-web-server
```

**Comment by 462960** [comment]
Thanks for support! I installed it locally and was expecting some result...

**Comment by 75lb** [comment]
when installed locally, you can run it like this: 

```
$ ./node_modules/.bin/ws
```

Or use [this method](https://github.com/lwsjs/local-web-server/wiki/how-to-distribute-local-web-server-with-your-project).

**Comment by 462960** [comment]
Thank you! It's handy because I have to ask admin for global installation.

**Comment by 75lb** [comment]
ah, ok.. then local installation is better 👍

**Comment by 462960** [comment]
Sorry to bother you, but my local-web-folder folder looks empty or locked by some reasons (has unusual mark) http://joxi.net/krDBDdNC0aOMp2
So,  $ ./node_modules/.bin/ws command produces "No such file or directory"
http://joxi.ru/KAxl9yOC4NB19A

**Comment by 75lb** [comment]
hmm, i'm sorry - i don't know.. maybe you installed it with `sudo` or a different account? I think you need to ask your admin.. It is not a bug with local-web-server.
