### ISSUE TITLE
How to run in a non root folder

### ISSUE THREAD

**Issue by uuykay** [lwsjs/local-web-server#90]
Hi there,

I'm trying to run local web server in a different directory. For example I wrote a NPM script to run the command:
ws ./core/connection/local_server/index.html

However I get a "Command not recognised" error. 

Can I run ws from my root folder, and get it to serve the contents of a different folder?

**Comment by 75lb** [comment]
Install `ws` globally with this command:

```
$ npm install -g local-web-server
```

The `ws` command will now be available in any folder.

If you serve the folder `/folder/one` but also want `/folder/two` to be served, you can create a symlink in `/folder/one` which points to `/folder/two`.

**Comment by uuykay** [comment]
Appreciate such a quick response. I know I can just change directories from my terminal, however I'd like to use my npm scripts located in the root of my project, and have ws serve a folder nested within my project.

I tried the symlink approach but could not get it to work. Was wondering if there is a command line arguement I can set to serve a custom directory rather than the current directory of my terminal.

**Comment by 75lb** [comment]
yes, the `--directory` option. E.g. 

```
$ ws --directory public
```

**Comment by uuykay** [comment]
Perfect, exactly what I wanted. Thanks again.
