### ISSUE TITLE
spa in config file is not recognized

### ISSUE THREAD

**Issue by maxorlovsky** [lwsjs/local-web-server#91]
While trying to play around to create middleware for issue #86 found bug with spa config.
When trying to put spa into lws.config.js it's not working, even though it appears in options.

This does not work

```
module.exports = {
    rewrite: [
        { from: '/api/*', to: '...api/public/$1' },
        { from: '/images/*', to: '.../images/$1' }
    ],
    directory: 'public',
    spa: 'index.html',
    https: true,
    port: 8080
}
```

What works is to remove spa from config and put it in command line as
```--spa index.html```

**Comment by 75lb** [comment]
i can't reproduce this, your config works fine for me. Could you supply more information on how exactly how to reproduce this please?

Also, what is this path: `'...api/public/$1'`? It looks invalid to me..

**Comment by 75lb** [comment]
FYI, i closed this until I get a reproduction case. I use `spa` in the `lws.config.js` file all the time, also many others do - no issues found yet. Are you sure the path `index.html` exists? If so, does the `index.html` path you supplied exist underneath the specified directory (`public`)?

**Comment by maxorlovsky** [comment]
`'...api/public/$1'` was an example
Updated LWS to latest, was on 2.3.0 and everything works like a charm. Have no idea why I was receiving blank page, but could not reproduce it myself. And as long as it work this bug is irrelevant.
Thank you @75lb :)

**Comment by 75lb** [comment]
ok, good 👍
