### ISSUE TITLE
Cannot find module 'lws/lib/usage'

### ISSUE THREAD

**Issue by stefan-orzu** [lwsjs/local-web-server#98]
I am using lws for mocking some API endpoints and everything worked fine until I've removed node_modules and ran `npm install` again.
Now starting the server (`ws -c mock-server/lws.config.js`) throws this error:
```
Error: Cannot find module 'lws/lib/usage'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at MockResponse.middleware (...\node_modules\lws-mock-response\index.js:42:21)
...
```
The configuration file (`mock-server/lws.config.js`) is very small : 
```
module.exports = {
    port: 8789,
    mocks: require('./mocks')
};
```
where mocks.js exports a lambda following the pattern from the documentation: 
```
module.exports = MockBase => class MockService extends MockBase {
    mocks(options) {
        return [...]; // several route configurations
    }
};
```
I've looked in node_modules/lws/lib and indeed there is no usage.js file.

Am I missing something here or is it a regression from the lws-mock-response module?

**Comment by stefan-orzu** [comment]
My guess is that this commit (https://github.com/lwsjs/lws/commit/b0319d8e8eeba20bae6091a3fa0620c3a70f25a6#diff-e8acc63b1e238f3255c900eed37254b8) broke the code for the lws-mock-response module: https://github.com/lwsjs/mock-response/blob/master/index.js#L42

**Comment by 75lb** [comment]
yes, you're right. Thanks for letting me know - fixing now. Will get back to you.

**Comment by 75lb** [comment]
Fixed in `lws-mock-response@0.5.1`. Please reinstall local-web-server. Let me know if there's anything else, thanks. 👍

**Comment by stefan-orzu** [comment]
I've reinstalled and everything works fine now. Thank you very much for the quick response and fix!

**Comment by tylermassey** [comment]
I also ran into this issue, but I've been using `local-web-server@2.5.2`. Anything to do besides upgrade to 2.5.6?

**Comment by 75lb** [comment]
the fix is in the latest version.. is there any reason you can't upgrade?

**Comment by tylermassey** [comment]
@75lb I can upgrade, so my team is okay, but I wanted to point it out because there may be others that will face this.
