### ISSUE TITLE
middleware bug EADDRINUSE 

### ISSUE THREAD

**Issue by baklanovavpulter** [lwsjs/local-web-server#99]
Win 8.1, node 10.6, latest local-web-server package, my own middleware for redirecting HTTP-requests based on lws-rewrite:
```JS
const _request = require('req-then');
// ...
let response = await _request(parsedUri, reqData);
```
Everything works fine almost 1 year with enough rate (requests/second). But several weeks ago (after NPM-packages update) I have found this bug:
```
16:56:09: Middleware error
Error: connect EADDRINUSE 188.42.29.80:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)
```
That appears irregular, but when you get it - it's useless to restart node app, only Windows reboot.

Did you ever get something similar?

**Comment by 75lb** [comment]
This error means that another server is already listening on port 80, this is not a bug with `ws`.
